[workspace]
resolver = "2"
members = [
    "crates/gifdex-appview",
    "crates/gifdex-ingest",
    "crates/gifdex-lexicons",
    "crates/doubletap",
    "crates/gifdex-cdn",
]

[profile.release]
lto = true
codegen-units = 1
